packaging: artik710: do not remove arm arch from devel package
ARM64 kernel arch header requires arm header, so removing arm arch
from artik710 devel package causes build error.

   ./arch/arm64/include/asm/opcodes.h:5:10: fatal error: ../../arm/include/asm/opcodes.h: No such file or directory
       5 | #include <../../arm/include/asm/opcodes.h>
         |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Do not remove arm arch from artik710 devel package.

Change-Id: Icf20808ebf50c42a9e74bf47d7345884168fa746
Signed-off-by: Seung-Woo Kim <sw0312.kim@samsung.com>